import { arraySidebar } from "vuepress-theme-hope";

export const Golang后端技术= arraySidebar([
    "",
    "分布式事务",
    "分布式事务框架DTM",
    "SAGA事务模式",
    "二阶段消息事务模式",
    "TCC事务模式",
    "XA事务模式",
    "其他事务模式",
    "AT vs XA",
    "异常与子事务屏障",
    "最终成功",
    "分布式锁",
    "CAP理论与PACELC模型",
    "语义化版本控制gsemver",
    "wire使用相关",
    "保证接口幂等性",
    "bash的一些知识",
    "如何设计RESTful接口",
    "testing单元测试及自动生成",
    "nacos-配置中心与注册中心",
    "Websocket包-nhooyr",
    "Websocket包-gobwas",
    "高性能网络包gnet",
    "Oauth2.0",
    "安装protobuf和使用GRPC",
    "GRPC传递与解析动态参数",
    "kafka包-kafka-go",
    "COW技术",
    "gorm"
]);